Gui:
    Game Name : "Pro Evolution Soccer 2014 SLES_535.44"
# You can get this offset with cheat engine
Game Data:
    Nation Start Address : 0x21944C38
    National Kit Length: 456
    Total National: 67
    Clubes Kit Length: 648
    Total Clubes: 130
    Teams Table Offset: 543562864 
    #Teams Table Size: 3152 # Total National + Total Clubes * 16 
    Teams Text Data Offset: 543554104
Settings:
    Process Name: "pcsx2.exe"